language: python

sudo: false

python:
- nightly
- 3.5
- 3.4
- 3.3
- 3.2
- 2.7

matrix:
  allow_failures:
  - python: nightly

addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran

before_install: PY=$(python -V 2>&1 | sed 's/[^0-9]//g;s/.//3g')

install:
- pip install tox
- tox -e py$PY --notest

script: tox -e py$PY
